// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7PGziAVF9jOMWTUQYPSJfsW67rhclpmo',
    appId: '1:484175567438:web:59d8367cc65978481f411f',
    messagingSenderId: '484175567438',
    projectId: 'flutter-calender-1dcda',
    authDomain: 'flutter-calender-1dcda.firebaseapp.com',
    databaseURL: 'https://flutter-calender-1dcda-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-calender-1dcda.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqWZOfJr_2IgKfpAD9fRsmKiw83Nrbxz4',
    appId: '1:484175567438:android:08ae44a3a48068ca1f411f',
    messagingSenderId: '484175567438',
    projectId: 'flutter-calender-1dcda',
    databaseURL: 'https://flutter-calender-1dcda-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-calender-1dcda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoPd4pu9obae4zUUcpsN8A2AHsWfC0ekc',
    appId: '1:484175567438:ios:9075fb0854fb4f291f411f',
    messagingSenderId: '484175567438',
    projectId: 'flutter-calender-1dcda',
    databaseURL: 'https://flutter-calender-1dcda-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-calender-1dcda.appspot.com',
    iosBundleId: 'com.example.flutterBookingOffers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoPd4pu9obae4zUUcpsN8A2AHsWfC0ekc',
    appId: '1:484175567438:ios:8e4a6b86d190ea541f411f',
    messagingSenderId: '484175567438',
    projectId: 'flutter-calender-1dcda',
    databaseURL: 'https://flutter-calender-1dcda-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-calender-1dcda.appspot.com',
    iosBundleId: 'com.example.flutterBookingOffers.RunnerTests',
  );
}
